<?php

/**
 *  2Moons 
 *   by Jan-Otto Kröpke 2009-2016
 *
 * For the full copyright and license information, please view the LICENSE
 *
 * @package 2Moons
 * @author Jan-Otto Kröpke <slaver7@gmail.com>
 * @copyright 2009 Lucky
 * @copyright 2016 Jan-Otto Kröpke <slaver7@gmail.com>
 * @licence MIT
 * @version 1.8.0
 * @link https://github.com/jkroepke/2Moons
 */

//LOSTPWD
$LNG['LOSTPWD_1']				= 'Pregunta a cambiar su contraseña';
$LNG['LOSTPWD_2']				= 'Si ha perdido su contraseña para acceder a su cuenta, debe completar este formulario.';
$LNG['LOSTPWD_3']				= 'La dirección de correo electrónico a entender es que su cuenta. Sin ella, no se puede cambiar su base de datos de autenticación.';
$LNG['LOSTPWD_4']				= 'Una vez validado, un correo electrónico será enviado automáticamente a su buzón.';
$LNG['LOSTPWD_5']				= 'El mensaje contendrá un enlace que le permite cambiar su contraseña de inicio de sesión.';
$LNG['LOSTPWD_6']				= 'En consecuencia, acepta recibir un correo electrónico de nuestros servicios mediante la validación de esta forma contra.';
$LNG['LOSTPWD_7']				= 'Cambiar contraseña';
$LNG['LOSTPWD_8']				= 'Volver a la página inicial';
$LNG['LOSTPWD_9']				= 'No hay ninguna cuenta asociada a esta dirección de correo electrónico en el universo seleccionado.';
$LNG['LOSTPWD_10']				= 'Cambiar contraseña';
$LNG['LOSTPWD_11']				= 'Usted está en el último paso, llenar el formulario para cambiar la contraseña de su cuenta con efecto inmediato.';
$LNG['LOSTPWD_12']				= 'Ultima actividad';
$LNG['LOSTPWD_13']				= 'IP';
$LNG['LOSTPWD_14']				= 'Expiración';
$LNG['LOSTPWD_15']				= 'Un correo electrónico ha sido enviado a la siguiente dirección : « %s ».<br>
					Contiene instrucciones sobre cómo cambiar su contraseña.';
$LNG['LOSTPWD_16']				= 'La contraseña de acceso a su cuenta « %s » se ha cambiado correctamente.';
//ERREUR404
$LNG['ERREUR_1']				= 'Dónde estás ? Te has perdido en el universo?';
$LNG['ERREUR_2']				= 'Dónde estás ?';
$LNG['ERREUR_3']				= 'Oh no ! ¿En serio? Un vórtice hubiera tragado esta página?';
$LNG['ERREUR_4']				= 'Página que no existe';
$LNG['ERREUR_5']				= 'Por favor, mantener la calma y volver a la página anterior.';
$LNG['ERREUR_6']				= 'Ir a la página principal';
$LNG['ERREUR_7']				= 'Yo quiero ir a casa';
$LNG['ERREUR_8']				= 'Ir a la página de registro';
$LNG['ERREUR_9']				= 'Darse de alta';
//ERREUR403
$LNG['ERREUR_10']				= 'Acceso prohibido';
$LNG['ERREUR_11']				= 'No se supone que estar aquí...';
$LNG['ERREUR_12']				= 'Usted no tiene permiso para acceder a esta página.';
$LNG['ERREUR_13']				= 'Página que no existe';
$LNG['ERREUR_14']				= 'Por favor, y vuélvete a una página que sea accesible por todos.';
//HOMEPAGE
$LNG['INDEX_1']					= 'Dirigida por Jeremy Baukens - Todos los derechos reservados -';
$LNG['INDEX_2']					= 'Acceder al foro de la comunidad ';
$LNG['INDEX_3']					= 'Comunidad';
$LNG['INDEX_4']					= 'Mostrar Pie de imprenta Sitio';
$LNG['INDEX_5']					= 'Notas legales';
$LNG['INDEX_6']					= 'Al continuar para navegar Antaris Legacy sin cambiar la configuración,
usted acepta el uso de cookies en su dispositivo &mdash;';
$LNG['INDEX_7']					= 'Aceptar y cerrar';
$LNG['INDEX_8']					= 'Cerca';
$LNG['INDEX_9']					= 'Para volver a la cima';
$LNG['INDEX_10']				= 'Acceder al menú';
$LNG['INDEX_11']				= 'Acceder a la página principal de Antaris Legacy';
$LNG['INDEX_12']				= 'Casa';
$LNG['INDEX_13']				= 'Breve presentación del juego';
$LNG['INDEX_14']				= 'Presentación';
$LNG['INDEX_15']				= 'Lee las reglas antes de empezar a jugar';
$LNG['INDEX_16']				= 'Reglas';
$LNG['INDEX_17']				= 'Lea las condiciones de uso de nuestros servicios';
$LNG['INDEX_18']				= 'Condiciones';
$LNG['INDEX_19']				= 'Enviar un correo electrónico al administrador del sitio';
$LNG['INDEX_20']				= 'Contacto';
$LNG['INDEX_21']				= 'Crea tu cuenta inmediatamente después de Antaris Legacy';
$LNG['INDEX_22']				= 'Registrar !';
$LNG['INDEX_23']				= 'Antaris Legacy : Inspirado en el universo Stargate.';
$LNG['INDEX_24']				= 'Del creador de Pegase Universo y Stargate Aventura.';
$LNG['INDEX_25']				= 'Antaris Legacy : Portal';
$LNG['INDEX_26']				= 'Bienvenido a un nuevo mundo de la ciencia ficción !';
$LNG['INDEX_27']				= 'Conectarse';
$LNG['INDEX_28']				= 'Antaris Legacy es un juego gratuito basado en el universo Stargate.';
$LNG['INDEX_29']				= 'Este juego fue creado por una organización independiente, sin conexión con la productora « MGM ».';
$LNG['INDEX_30']				= 'El registro es necesario para reproducirlo, se tarda menos de un minuto.';
$LNG['INDEX_31']				= 'Seleccione el universo';
$LNG['INDEX_32']				= 'Apodo';
$LNG['INDEX_33']				= 'Contraseña';
$LNG['INDEX_34']				= 'Jugar !';
$LNG['INDEX_35']				= 'Contraseña olvidada ?';
$LNG['INDEX_36']				= 'Regístrese ahora !';
$LNG['INDEX_37']				= 'Lista de universo';
$LNG['INDEX_38']				= 'Universo';
$LNG['INDEX_39']				= 'Estatus';
$LNG['INDEX_40']				= 'Fecha de inicio';
$LNG['INDEX_41']				= 'N°. registrado';
$LNG['INDEX_42']				= 'N°. conectado';
$LNG['INDEX_43']				= 'Lo último de Antaris Legacy';
$LNG['INDEX_44']				= 'escrito por';
//REGISTER
$LNG['REGISTER_1']				= 'inscribirse en un universo';
$LNG['REGISTER_2']				= 'abierto';
$LNG['REGISTER_3']				= 'Para inscribirse en el universo de Antaris Legacy, por favor complete la siguiente información.<br /><span class="color-blue">Una vez completado el registro, recibirá un correo electrónico que contendrá un enlace para activar su cuenta.';
$LNG['REGISTER_4']				= '¿Le crear o recuperar un mundo existente?';
$LNG['REGISTER_5']				= 'Para los jugadores <span class="color-blue">principiantes o confirmados</span>';
$LNG['REGISTER_6']				= 'Crear un mundo';
$LNG['REGISTER_7']				= 'Reunir un mundo';
$LNG['REGISTER_8']				= 'Para los jugadores <span class="color-blue">confirmados solamente</span>';
$LNG['REGISTER_9']				= 'Si usted es un principiante y nunca han jugado previamente en Antaris Legacy, le recomendamos que cree una cuenta desde cero.';
$LNG['REGISTER_10']				= 'Crear nueva cuenta';
$LNG['REGISTER_11']				= 'El apodo para acceder a su cuenta.';
$LNG['REGISTER_12']				= 'La contraseña para iniciar sesión.';
$LNG['REGISTER_13']				= 'Confirmación';
$LNG['REGISTER_14']				= 'Confirmación de la contraseña';
$LNG['REGISTER_15']				= 'Correo electrónico';
$LNG['REGISTER_16']				= 'La dirección de cuenta de correo electrónico (propietario).';
$LNG['REGISTER_17']				= 'Nombre planeta';
$LNG['REGISTER_18']				= 'Nombre del planeta';
$LNG['REGISTER_19']				= 'El nombre de su planeta madre.';
$LNG['REGISTER_20']				= 'Introducir el código';
$LNG['REGISTER_21']				= 'Código';
$LNG['REGISTER_22']				= 'Sistema para bloquear los robots.';
$LNG['REGISTER_23']				= 'He leído y acepto las reglas del juego';
$LNG['REGISTER_24']				= 'Lea las reglas del juego en su totalidad';
$LNG['REGISTER_25']				= 'Leer todo';
$LNG['REGISTER_26']				= 'He leído y acepto los términos y condiciones';
$LNG['REGISTER_27']				= 'Lea los términos y condiciones';
$LNG['REGISTER_28']				= 'Registro gratuito !';
$LNG['REGISTER_29']				= 'Confirmar contraseña.';
$LNG['REGISTER_30']				= 'La contraseña debe tener entre 6 y 32 caracteres.';
$LNG['REGISTER_31']				= 'La contraseña se ha introducido correctamente.';
$LNG['REGISTER_32']				= 'La contraseña para entrar.';
$LNG['REGISTER_33']				= 'La contraseña debe tener entre 6 y 32 caracteres.';
$LNG['REGISTER_34']				= 'La confirmación de la contraseña es incorrecta.';
$LNG['REGISTER_35']				= 'La confirmación coincide con la contraseña.';
$LNG['REGISTER_36']				= 'Confirmar contraseña.';
$LNG['REGISTER_37']				= 'Este nombre ya está en uso.';
$LNG['REGISTER_38']				= 'El apodo debe tener entre 3 y 16 caracteres.';
$LNG['REGISTER_39']				= 'El apodo se llena adecuadamente.';
$LNG['REGISTER_40']				= 'El apodo para acceder a su cuenta.';
$LNG['REGISTER_41']				= 'Este correo electrónico ya está en uso.';
$LNG['REGISTER_42']				= 'Su dirección de correo electrónico no es válida.';
$LNG['REGISTER_43']				= 'La dirección de correo electrónico es válida.';
$LNG['REGISTER_44']				= 'La dirección de cuenta de correo electrónico (propietario).';
$LNG['REGISTER_45']				= 'El nombre debe tener entre 5 y 18 caracteres.';
$LNG['REGISTER_46']				= 'Sólo letras, números, espacios y «-».';
$LNG['REGISTER_47']				= 'El nombre del planeta se ha completado correctamente.';
$LNG['REGISTER_48']				= 'El nombre de su planeta madre';
$LNG['REGISTER_49']				= 'Por favor proporcione su nombre de usuario para acceder a su cuenta.';
$LNG['REGISTER_50']				= 'Por favor, introduzca la dirección de correo electrónico de la cuenta (propietario).';
$LNG['REGISTER_51']				= 'Por favor, introduzca un nombre para su planeta madre / primaria.';
$LNG['REGISTER_52']				= 'Por favor, acepta en su totalidad solución del juego.';
$LNG['REGISTER_53']				= 'Por favor, acepta los términos y condiciones.';
$LNG['REGISTER_54']				= 'Confirmación y la contraseña no son idénticos.';
$LNG['REGISTER_55']				= 'Su dirección de correo electrónico no es válida.';
$LNG['REGISTER_56']				= 'Su nombre de usuario no es válido.';
$LNG['REGISTER_57']				= 'El nombre de nuestro planeta debe contener sólo letras, números, guiones y espacios.';
$LNG['REGISTER_58']				= 'Por favor, introduzca una dirección de correo electrónico diferente debido a que ya se utiliza.';
$LNG['REGISTER_59']				= 'Por favor, introduzca un nombre de usuario diferente porque ya se utiliza.';
$LNG['REGISTER_60']				= 'Su cuenta ha sido creada con éxito el universo « Horizon ».<br />Sin embargo, es necesario activarlo desde su buzón de correo.';
$LNG['REGISTER_61']				= 'Si usted no ha recibido el correo electrónico de validación, revisar su correo basura (SPAM).';
$LNG['REGISTER_62']				= 'Una clave de activación ha sido enviada a la dirección de correo electrónico que ha introducido.';
$LNG['REGISTER_63']				= 'Si no ha recibido ningún mensaje en su bandeja de entrada, compruebe si no es en su spam.';
$LNG['REGISTER_64']				= 'Usted tiene 7 días para activar su cuenta antes de que se elimina permanentemente.';
$LNG['REGISTER_65']				= 'Por favor, introduzca el código de seguridad que permite asegurar que no eres un robot.';
$LNG['REGISTER_66']				= 'El código de seguridad que ha especificado no es válido.';
$LNG['REGISTER_67']				= 'El código de seguridad no es válida.';
$LNG['REGISTER_68']				= 'Sistema para bloquear los robots';
$LNG['REGISTER_69']				= 'El código « anti-bot » es válida';
$LNG['REGISTER_70']				= 'Por favor, introduzca una contraseña para acceder a su cuenta.';
$LNG['REGISTER_71']				= 'Por favor, introduzca una nueva contraseña para acceder a su cuenta.';
$LNG['REGISTER_72']				= 'Antaris Legacy - Registro en el portal';
//CONTACT
$LNG['CONTACT_0']				= 'Contáctenos';
$LNG['CONTACT_1']				= 'Póngase en contacto con nosotros por correo electrónico';
$LNG['CONTACT_2']				= 'Puede ponerse en contacto con el « Antaris Legacy » administrador del sitio a través del siguiente formulario.';
$LNG['CONTACT_3']				= 'Sabiendo que está estrictamente prohibido en contacto con nosotros por motivos relacionados con el juego en sí, ';
$LNG['CONTACT_4']				= 'es decir, los insectos, las quejas y solicitudes de asistencia.';
$LNG['CONTACT_5']				= 'Recordamos a nuestros visitantes y nuestros jugadores es posible pedir ayuda y hacer preguntas en nuestro foro comunitario.';
$LNG['CONTACT_6']				= 'Un miembro de nuestro equipo esperamos poder responder a sus preguntas.';
$LNG['CONTACT_7']				= 'Al llenar el formulario a continuación, tomar nota de que recibirá un correo electrónico de « copie » de nosotros.';
$LNG['CONTACT_8']				= 'También autoriza a proteger su IP para fines técnicos.';
$LNG['CONTACT_9']				= 'Rellene el formulario de contacto';
$LNG['CONTACT_10']				= 'Su nombre o apodo';
$LNG['CONTACT_11']				= 'Nombre o apodo';
$LNG['CONTACT_12']				= 'Su dirección de correo electrónico';
$LNG['CONTACT_13']				= 'Título del mensaje';
$LNG['CONTACT_14'][1]			= 'Solicitud de contratación';
$LNG['CONTACT_14'][2]			= 'Solicitud de asociación';
$LNG['CONTACT_14'][3]			= 'Las preguntas sobre las compras in-app';
$LNG['CONTACT_14'][4]			= 'Problema durante una compra de PayPal';
$LNG['CONTACT_14'][5]			= 'Bug bloquea totalmente su cuenta';
$LNG['CONTACT_14'][6]			= 'Otro';
$LNG['CONTACT_19']				= 'Vuestro mensaje';
$LNG['CONTACT_20']				= 'Su mensaje aquí...';
$LNG['CONTACT_21']				= 'Anti-Robot';
$LNG['CONTACT_22']				= 'Envíe su mensaje';
$LNG['CONTACT_23']				= 'Notas legales';
$LNG['CONTACT_24']				= 'Editorial y la sede';
$LNG['CONTACT_25']				= 'El sitio « Antaris Legacy » en su conjunto está gestionado y mantenido por un voluntario.';
$LNG['CONTACT_26']				= 'información';
$LNG['CONTACT_27']				= 'Nombre del consejero';
$LNG['CONTACT_28']				= 'Directora de la publicación';
$LNG['CONTACT_29']				= 'Dirección postal';
$LNG['CONTACT_30']				= 'Teléfono';
$LNG['CONTACT_31']				= 'Solicitud por correo electrónico';
$LNG['CONTACT_32']				= 'Alojamiento';
$LNG['CONTACT_33']				= 'Los sitios web Antaris heredados están alojados en nuestro proveedor : OVH';
$LNG['CONTACT_34']				= 'información';
$LNG['CONTACT_35']				= 'Anfitrión';
$LNG['CONTACT_36']				= 'Dirección del host';
$LNG['CONTACT_37']				= 'Por favor, introduzca su identidad: nombre y apellido o sobrenombre.';
$LNG['CONTACT_38']				= 'Por favor, introduzca una dirección de correo electrónico.';
$LNG['CONTACT_39']				= 'Por favor, introduzca una dirección de correo electrónico que sea válida.';
$LNG['CONTACT_40']				= 'Por favor, escriba un mensaje para ser enviado.';
$LNG['CONTACT_41']				= 'Su mensaje debe contener más de 25 caracteres.';
$LNG['CONTACT_42']				= 'El tema elegido no es válido.';
$LNG['CONTACT_43']				= 'Su mensaje ha sido enviada al administrador del sitio. Usted recibirá una copia de su buzón.';
$LNG['CONTACT_44']				= 'Por favor, introduzca el código de seguridad.';
//PRESENTATION
$LNG['PRESENTATION_1']			= 'Presentación';
$LNG['PRESENTATION_2']			= 'Antaris Legacy es un navegador de estrategia de gestión de la caza / multijugador masivo, 
		basado en un universo de ciencia ficción enteramente inventado.';
$LNG['PRESENTATION_3']			= '¿Tiene suficiente material para tomar parte en la lucha por participar en grandes batallas, explorar lo desconocido, y construir su propio imperio 
		Embarcarse ahora en un universo de ciencia ficción sin límites: la conquista del espacio y sus tierras inexploradas,
colonizar muchos planetas para expandir su imperio y aumentar su poder, no evolucionar su tecnología y edificios,
formar su propio ejército y su flota espacial para luchar contra las fuerzas de sus enemigos con sus aliados o solos.';
$LNG['PRESENTATION_4']			= '¿Cree que puede competir con otras naciones para imponer su ideología, sus leyes ? 
		Unirse a los jugadores que ya la espera de que la batalla !';
$LNG['PRESENTATION_5']			= 'Descubre un espacio único y juego de tierra en su género, donde la comunidad cálida y
La solidaridad sólo pide para ampliar y pasar tiempo de calidad con usted.';
$LNG['PRESENTATION_6']			= 'Presentación imagen';
$LNG['PRESENTATION_7']			= 'Sala de Control';
$LNG['PRESENTATION_8']			= 'Sensores interestelares';
$LNG['PRESENTATION_9']			= 'Portal de teletransporte';
$LNG['PRESENTATION_10']			= 'Centro espacial';
$LNG['PRESENTATION_11']			= 'Edificios';
$LNG['PRESENTATION_12']			= 'Tecnologías';
$LNG['PRESENTATION_13']			= 'Equipo especializado';
$LNG['PRESENTATION_14']			= 'Defensas';
$LNG['PRESENTATION_15']			= 'Poblaciones';
$LNG['PRESENTATION_16']			= 'Banco: la evolución del mercado';
$LNG['PRESENTATION_17']			= 'Estadísticas del universo';
$LNG['PRESENTATION_18']			= 'Misión para principiantes';
$LNG['PRESENTATION_19']			= 'Internets navegadores compatibles';
$LNG['PRESENTATION_20']			= 'El juego dispone de los últimos lenguajes de programación (<em>en particular, CSS3, HTML5 y el jQuery</em>), en consecuencia,
su navegador web debe ser actualizado regularmente para jugar en las mejores condiciones posibles. 
		<strong>Se recomienda encarecidamente el uso de Mozilla Firefox o Google Chrome.</strong>';
$LNG['PRESENTATION_21']			= 'Logotipo de Chrome';
$LNG['PRESENTATION_22']			= 'Versión <strong>5 y más</strong>';
$LNG['PRESENTATION_23']			= 'El sitio de Google Chrome';
$LNG['PRESENTATION_24']			= 'Logotipo de Mozilla Firefox';
$LNG['PRESENTATION_25']			= 'El sitio de Mozilla';
$LNG['PRESENTATION_26']			= 'Versión <strong>4 y más</strong>.';
$LNG['PRESENTATION_27']			= 'Logotipo de Safari de Apple';
$LNG['PRESENTATION_28']			= 'Versión <strong>4.* y más</strong>';
$LNG['PRESENTATION_29']			= 'El sitio de Safari';
$LNG['PRESENTATION_30']			= 'Logotipo deInternet explorar';
$LNG['PRESENTATION_31']			= 'Versión <strong>9 y más</strong>';
$LNG['PRESENTATION_32']			= 'El sitio de Internet Explorer';
$LNG['PRESENTATION_33']			= 'Porcentajes / estadísticas que se obtuvieron a través de Google Analytics « antaris-legacy.co », 6 de enero de, el año 2016. *';
//RULES
$LNG['RULES_1'] 				= 'Reglas del juego';
$LNG['RULES_2'] 				= 'Multi-cuenta';
$LNG['RULES_3'] 				= 'Anónimo navegación';
$LNG['RULES_4'] 				= 'Cogestión';
$LNG['RULES_5'] 				= 'Donaciones cuenta';
$LNG['RULES_6'] 				= 'Cuenta del Préstamo';
$LNG['RULES_7'] 				= 'Pausa';
$LNG['RULES_8'] 				= 'Contraseña: seguridad';
$LNG['RULES_9'] 				= 'Seudo robo';
$LNG['RULES_10'] 				= 'La comunicación Antaris Legacy';
$LNG['RULES_11'] 				= 'Eliminar cuenta';
$LNG['RULES_12'] 				= 'Cuentas';
$LNG['RULES_13'] 				= 'Las reglas del comercio - Push';
$LNG['RULES_14'] 				= 'Pacto Out';
$LNG['RULES_15'] 				= 'El tipo de comercio / Push';
$LNG['RULES_16'] 				= 'Cuenta « latente »';
$LNG['RULES_17'] 				= 'Elusión de las normas comerciales';
$LNG['RULES_18'] 				= 'Los ataques';
$LNG['RULES_19'] 				= 'Tiempo de guerra';
$LNG['RULES_20'] 				= 'Tregua General';
$LNG['RULES_21'] 				= 'Alianzas';
$LNG['RULES_22'] 				= 'Tiempo de guerra';
$LNG['RULES_23'] 				= 'Bugs/errores';
$LNG['RULES_24'] 				= 'Ayudas técnicas';
$LNG['RULES_25'] 				= 'Bugs y errores';
$LNG['RULES_26'] 				= 'Los insultos y amenazas';
$LNG['RULES_27'] 				= 'Requisitos particulares para el chat';
$LNG['RULES_28'] 				= 'Respeto Reglamento';
$LNG['RULES_29'] 				= 'Sanciones';
$LNG['RULES_30'] 				= "Inconvenientes";
$LNG['RULES_31'] 				= 'Responsabilidades y cambios';
$LNG['RULES_32'] 				= 'Reglas del juego';
/* $LNG['RULES_33']				= 'Cualquier jugador que acepta el acuerdo, aceptar las consecuencias, incluidas las posibles sanciones.       La regulación puede ser cambiada en cualquier momento sin previo aviso. Por supuesto, pueden hacer anuncios foro o en el juego, a raíz de los cambios.<br /><br />            Además, las nuevas reglas tienen efecto retroactivo, el usuario no puede oponerse a ella a menos que retire todas sus cuentas de nuestros servicios.<br /><br />        Antaris legado no se hace responsable de desventaja o de otra manera, causada como resultado de un error.';
$LNG['RULES_34']				= 'Para volver al principio';
$LNG['RULES_35']				= 'Volver al principio';
$LNG['RULES_36']				= 'Recordamos que los jugadores no pueden reclamar un reembolso cuando sus cuentas sufren una o más bugs / errores.       Si la mayoría de los jugadores se ven afectados por un error, el personal puede decidir realizar una copia de seguridad posible (hacia atrás) en función de la gravedad de la misma.       Las copias de seguridad no se pueden realizar en una sola cuenta.<br /><br />        Un jugador no puede pedir una indemnización después de una pérdida de las acciones realizadas en su cuenta durante un flashback del universo.';
$LNG['RULES_37']				= 'El incumplimiento incluido en esta regulación puede resultar en una sanción al infractor cuenta tanto el juego como en el foro.       Además, de conformidad con las condiciones generales, una cuenta de usuario y la  « física » puede ser prohibido de todos los servicios ofrecidos por Antaris Legado de manera temporal o definitiva. Un administrador o moderador puede volver a prohibir una cuenta perteneciente a un usuario que está registrado (sin pasar por los medios de verificación técnica o no) a pesar de su expulsión permanente o temporal.<br /><br />        En caso de violación de los reglamentos, los moderadores y administradores del personal son los únicos que van a decidir la pena que se aplicarán.       Además, el personal se reserva el derecho de rechazar y / o sancionar cualquier cosa que pueda perjudicar a la ética o el desarrollo del juego.       Será castigado cualquier conducta perjudicial para el ambiente general de la tchat.<br /><br />        La duración de la pena y el castigo aplicado solo depende de la resolución dictada por el moderador.       Las sanciones varían: advertencia, prohibición temporal que va desde 1 día hasta varios años o de forma permanente y / o expulsión de la entrevista.<br /><br />        La sanción puede ser impugnada en el foro, en el «Queja», el título del tema debe ser escrito de la siguiente manera : «Apodo impugnar una sanción».       Para ser lo más justo posible, la pena asignada por el moderador será revisada por otro miembro del personal, en la medida posible solamente.<br /><br />              Cuentas prohibidos no pueden ser atacados por la duración de la pena. Sin embargo, durante la aplicación de la sanción, la cuenta del jugador se retira de la primera pausa, en caso de que se active. Este modo no se reactiva al final de la frase. Añadir el jugador para hacer una pausa en sí después del período de prohibición.';
$LNG['RULES_38']				= 'Chat en general se considera un servicio opcional que se puede quitar en cualquier momento sin que el usuario para oponerse a ella.<br /><br />              Por lo tanto, un miembro del equipo de Antaris Legacy, si moderador o administrador puede transferir (es decir, la prohibición temporal o permanentemente reproductor de chat general) sin tener que justificar ante del usuario en cuestión. La decisión no puede ser cuestionada ya que el « silencio » no prohíbe el acceso a los elementos esenciales de la cuenta.<br /><br />              Está estrictamente prohibido poner las coordenadas mundo (excepto planeta de origen) en la charla en general, y de la composición de un ejército que no sean sus propios o enfrentar sanciones.       Si necesita transmitir, dar por mensaje privado o un susurro. También está prohibido hacer publicidad de otro navegador juego.';
$LNG['RULES_39']				= 'Queremos recordar que este es un juego, mantener una actitud correcta y respetable hacia otros jugadores en nuestra comunidad.<br /><br />        Está estrictamente prohibido escribir mensajes insultantes y / o falta de respeto (la discriminación, el racismo, la homofobia, la pornografía).      Del mismo modo , los mensajes destinados únicamente para provocar insultos desde el interlocutor con el fin de hacer que la prohibición está prohibido y castigado .       Algunos miembros de la comunidad pueden ser jóvenes adolescentes , por lo tanto , las palabras pueden herir la sensibilidad más jóvenes están prohibidas       en el juego , al igual que en los foros.<br /><br />        Las reglas anteriores se aplican también a los apodos , los nombres de los planetas , nombres , descripciones de la alianza alianzas , mensajes públicos (chatear) y privada ( mensaje privado o alianza ) .<br /><br />       Todas las amenazas que salen del contexto del juego ( las amenazas en el contexto del juego de roles permitido ) están estrictamente prohibidos . El moderador es el único que puede arreglar la frontera / límite entre el juego de roles y  «real». Se puede tomar sanciones en consecuencia.<br /><br />       Un jugador puede hacer una queja en el foro , en la sección «Quejas» , si una comunidad de jugadores no respetan las normas enumeradas en el presente apartado .';
$LNG['RULES_40']				= 'Antaris Legacy es un juego en constante evolución , puede suceder que se cumple con algún error o errores durante su aventura . Estos errores deben informar de inmediato al Foro en el  «Bug y errores» sección.<br /><br />     Está estrictamente prohibido el uso de bugs / errores a su favor , bajo pena de sanción elevada .      No divulgación de un error encontrado ( beneficioso o no ) también dará lugar a una sanción .<br /><br />      Si error , es posible que aparezca un mensaje de error en la pantalla , para ayudarnos a corregirlo tan pronto como sea posible , por favor, guarde este mensaje y lo remitirá al personal a través del Foro .<br /><br />        El personal no se hace responsable de los problemas con un error . El equipo de Antaris legado no reembolsará las pérdidas a un error . Solamente los insectos durante una transacción de Paypal o Allopass será devuelto ( después de la presentación de la evidencia : el código Allopass o el número de transacciones de PayPal ) .';
$LNG['RULES_41']				= 'Está estrictamente prohibido el uso de bots o scripts para automatizar acciones en el juego . El usuario debe utilizar un navegador estándar para jugar en su cuenta ( Mozilla Firefox , Internet Explorer , Safari , Chrome , etc ... ) . También se prohíbe el uso de complementos . El administrador del juego puede desterrar vida sin previo aviso , un jugador no respetar la prohibición oficial mencionado anteriormente .<br /><br />       Los usuarios pueden crear y utilizar documentos de Word / Excel para realizar copias de seguridad de datos y / o las coordenadas de los planetas , sin embargo , está estrictamente prohibido para escanear toda la galaxia por medios automáticos.';
$LNG['RULES_42']				= 'En la guerra, un jugador debe esperar por lo menos 72 horas después del inicio de la guerra para salir de su alianza ( que también está prohibido el envío de un jugador de su alianza durante este período) .       Además, un jugador no puede salir de la alianza entre el momento de la declaración de guerra y el comienzo . El incumplimiento puede dar lugar a una sanción .<br /><br />      En tiempos de paz , el jugador puede salir de la alianza en cualquier momento.';
$LNG['RULES_43']				= 'Cualquier jugador tiene el derecho de decidir fundar una alianza , sin embargo, cualquier alianza debe respetar las reglas básicas , como un nombre decente , la página de inicio correcta con un texto sin provocación y sin imágenes impactantes .<br /><br />        Cualquier presentación de la alianza , un insulto o una falta de respeto ( la discriminación , el racismo , la homofobia , la pornografía ) estará sujeta a una sanción .<br /><br />       El fundador es el único responsable por el contenido de la descripción de su pacto , y él le dará a los derechos de publicación únicamente a personas de su confianza . Si la descripción no se ajusta a las normas expuestas anteriormente , el fundador de la alianza será prohibido de forma temporal o permanentemente del juego .<br /><br />       Las alianzas pueden establecer regulaciones internas , si respeta las reglas de Antaris legado de la legislación francesa , la doctrina y la moral .';
$LNG['RULES_44']				= 'El personal puede decidir la creación de una tregua en general el mundo por varias razones :       <ul>         <li>por períodos o días específicos</li>         <li>después de un servicio que no se obtuvo</li>         <li>después de cualquier error en los ataques</li>       </ul>             En una tregua general, ningún ataque se tolera , sin embargo , se permite el espionaje .<br /><br />             El sistema que se encarga únicamente los bloques de tregua generales <u>lanzamiento</u> ataques durante la tregua . Por lo tanto , el jugador que tiene que cancelar de forma manual y debe ataques espaciales antes del descanso y culminando durante el mismo. De no hacerlo, podría justificar la presentación de una queja ante el jugador sufre ataque no normativo .';
$LNG['RULES_45']				= 'Una alianza puede declarar la guerra al mismo tiempo contra otras alianzas 4 como máximo. Sabiendo que no podemos declarar la guerra a una alianza ya en guerra contra otros 7 alianzas . Una guerra de duración limitada que se fijará entre 14 y 31 días . La declaración de guerra debe hacerse con 72 horas de antelación del foro.<br /><br />             Además , hay un período mínimo de 24 horas antes del comienzo de la guerra, donde no hay ataques pueden ser lanzados contra un jugador de una parte de la alianza de la guerra declarada . Si un miembro del personal decide , este plazo podrá ampliarse sin explicación proporciona . Del mismo modo , las guerras fechas pueden ser modificadas por el moderador, si lo considera necesario .<br /><br />       Las reglas de ataques en tiempo de guerra son :       <ul>         <li>Un jugador sólo puede atacar 12 veces en un ciclo de 72 horas, a otro jugador .</li>         <li>Ciclo de 72 horas que contiene uno o más 24 ciclos .</li>         <li>El atacante puede atacar sólo 6 veces un ciclo de 24 horas .</li>         <li>El jugador sólo puede atacar una vez por ciclo de 24 horas , el mismo planeta a través del portal de teletransporte .</li>       </ul>       Una guerra debe ser declarado sólo por el fundador de la alianza en cuestión. Si se viola esta regla , la guerra sólo puede cancelarse por la decisión de un moderador .<br /><br />              Cuando la guerra ha terminado , no es posible redeclare otra contra las mismas alianzas anteriores dentro de los 14 días .       Alianzas que se componen de un solo miembro no pueden construido una guerra ( el fundador puede ser sancionado por el incumplimiento de esta regla ) .';
$LNG['RULES_46']				= 'Los ataques se les prohíbe a las siguientes cuentas :       <ul>         <li>en pausa.</li>         <li>que pertenece a un miembro del personal .</li>         <li>más débil o más fuerte que la suya ( límite superior / inferior ) .</li>         <li>Multi- cuenta con el suyo (la misma dirección IP ) .</li>         <li>aliado con usted ( Pacto del Automóvil , miembro de la misma alianza , etc ... ) .</li>       </ul>        Debe tener en cuenta los siguientes ataques :       <ul>         <li>Un jugador puede atacar sólo 6 veces en un ciclo de 72 horas , otro jugador .</li>         <li>Ciclo de 72 horas que contiene uno o más 24 ciclos .</li>         <li>El atacante puede atacar sólo 3 veces un ciclo de 24 horas .</li>         <li>El jugador sólo puede atacar una vez por ciclo de 24 horas , el mismo planeta a través del portal de teletransporte .</li>       </ul>             Ataca a un sistema de gestión de bloques Los atentados que no respetan las normas de seguridad. Sin embargo , por favor, póngase en contacto con el personal en caso de problemas con el gestor de ataque.<br /><br />             Está estrictamente prohibido para eludir el límite de ataque de alta / baja al hacer un préstamo a otro jugador con el único propósito de cambiar sus puntos . Cualquier elusión de este límite , y cualquiera que sea el medio empleado , serán sancionadas por un miembro del personal .<br /><br />        Por último , el personal puede establecer una tregua general sobre el servidor , después de un mantenimiento que no se esperaba, o después de cualquier fallo en el ataque . Durante la tregua , ningún ataque se tolera , sin embargo , se permite el espionaje .';
$LNG['RULES_47']				= 'Cualquier elusión o bloqueos del juego , por cualquier medio , se considera como una violación de los reglamentos y por lo tanto punible .<br /><br />        lista no exhaustiva de las acciones prohibidas en el juego :       <ul>         <li>Voluntariamente aumentar la masa de recursos intercambiados entre dos cuentas para ser favorecido por el 25% del rango permitido .</li>         <li>Intruso de forma voluntaria tropas y equipos en un jugador más fuerte .</li>         <li>Se prohíben los ataques organizados .</li>         <li>El comercio triangular dice que está prohibido ( utilizar a terceros para superar el bloqueo de cuentas en múltiples ) .</li>       </ul>              Un jugador sin pasar por el mismo, podrá ser objeto de sanciones de hasta el bloqueo definitivo de la cuenta .';
$LNG['RULES_48']				= 'Una cuenta « latente » cuenta está estancada ( jugador ya no desarrolla su nombre ) , que se utiliza en el único objetivo de producir población, recursos y equipos para enviar a la cuenta de otro jugador o un grupo de jugadores . Cualquier transacción del tipo está prohibida . Cada jugador que participa en dichas operaciones se castiga con la expulsión .';
$LNG['RULES_49']				= ' El comercio entre los dos jugadores deben cumplir con las siguientes tarifas (con un margen de error del 25 % ) para ser justos :       <ul>         <li>Contacto: Hierro = 4 unidades 3 unidades de oro = 2 unidades = 1 unidades de cristal Elyrium .</li>         <li>Dispositivo: convertir sólo el precio unitario de acuerdo a las tarifas anteriores .</li>         <li>Población : 1 unidad de entrenamiento = 20 unidades de hierro .</li>       </ul>        Cambio dura un máximo de 48 horas . Sin embargo, si al final de este período , el intercambio se realiza siempre injusta , a continuación , empuje el sistema le dará un período adicional de 24 para ponerlo en buen estado. Después de estas 24 horas , si el intercambio sigue siendo injusta , debe solicitar un empujón en el foro en la sección correspondiente . Un moderador se encargará de su solicitud y el tratamiento de los temas , caso por caso , ( que no quiere decir que usted puede ser prohibido por el incumplimiento de la regla ) .<br /><br />       Si se encuentra en una situación irregular después de un intercambio desigual se ha completado ( últimas 72 horas) y no se ha hecho un «empuje de la demand» en el foro, a continuación, las dos cuentas ofensivas serán castigados sin previo aviso .<br /><br />        Los jugadores tienen a su disposición una página haciéndoles saber si su comercio es justo o no . Para ello, vaya a la página de « Comercio » y la pestaña « Push» .<br /><br />       Una cuenta que se utiliza exclusivamente para abastecer a otro , será suspendido de por vida , y la cuenta de «receptor» será castigado de manera ejemplar .';
$LNG['RULES_50']				= 'Durante un pacto descanso (entre el jugador o automáticamente) , debe esperar 24 horas antes de atacar a su ex aliado . El fracaso de la tregua de 24 horas puede resultar en una sanción .';
$LNG['RULES_51']				= 'Comercio sólo es válida si se produce un intercambio entre dos jugadores ( las siguientes reglas no se aplican a la utilización del banco) .<br /><br />        Para realizar transacciones comerciales , debe en primer lugar que ambos jugadores tienen un pacto . El pacto puede ser automática ( es decir , dos jugadores que están en la misma alianza no necesitarán hacer pacto entre ellos para el comercio , así , por dos jugadores que están en alianzas «amigos »).<br /><br />       Está estrictamente prohibido el envío de recursos a un jugador fuerte y sin un retorno justo (respeto de la tasa del comercio ) en un período de 48 horas después de que el primer envío .';
$LNG['RULES_52']				= 'Legado Antaris retiene , para, los datos personales de carácter puramente técnico de su cuenta por un período limitado de 10 días después de la solicitud de eliminación él. Sus datos personales se elimina totalmente y permanentemente de nuestros servidores después de este tiempo .<br /><br />              Sin embargo , usted siempre tiene la opción de solicitar la retirada tan pronto como sea posible de sus datos personales poniéndose en contacto con el administrador a través de email : staff@antaris-legacy.co';
$LNG['RULES_53']				= 'El personal se reserva el derecho a leer los mensajes, incluidos los mensajes intercambiados entre los jugadores , para verificar el cumplimiento . Es decir , que los sistemas disponibles en el juego para comunicarse ( por ejemplo, los susurros en el «Chat» o mensajes privados , etc ... ) se pueden usar en su contra en caso de conflicto .<br /><br />              Al registrarse en uno de nuestro universo , debe dar permiso al personal para leer todos sus mensajes. Esta autorización se cancela automáticamente sólo mediante la supresión de su cuenta .<br /><br />        Si usted desea tener conversaciones privadas con otro jugador, usted tiene que utilizar otros medios de comunicación: Skype , MSN , Facebook , etc ... ;
$LNG['RULES_54']				= 'El apodo de robo es la deliberada teniendo un pseudo casi idéntico a otro jugador del universo con el fin de sembrar la confusión . Está estrictamente prohibido intentar apropiarse el apodo de otro jugador , incluso utilizando algunas variantes ( o unas pocas letras que son diferentes pero que se parecen ) .       <br />Ejemplo : el seudo Tom con una mayúscula «O» y seudo T0M con el número cero .';
$LNG['RULES_55']				= 'La contraseña es la seguridad que impide que otra persona acceda a su cuenta , se recomienda elegir una difícil de encontrar ( no poner su nombre , por ejemplo) , por lo menos 8 caracteres con letras , números y caracteres especiales.<br /><br />       Su contraseña no debe ser revelada . El personal nunca le pedirá su contraseña. Sin embargo , para hacer una cuenta de préstamo , debe proporcionar su contraseña a otro jugador . El personal no se hace responsable en caso de problemas en esta situación .<br /><br />        Las contraseñas están encriptadas por nuestros servidores . Por lo tanto , las cuentas no pueden ser pirateadas que en caso de que la contraseña es demasiado simple .';
$LNG['RULES_56']				= 'El modo de pausa se ​​activa mediante el «perfil» de la cuenta . La duración mínima de la pausa es de 72 horas . Debe esperar un mínimo de 48 horas antes de que pueda recuperarse en pausa .<br /><br />              La ruptura hace que el cese de la producción de todos los recursos . Sin embargo , construcciones , desarrollos y población de la producción siguen teniendo lugar durante el descanso .<br /><br />          Las cadenas y los modos rápidos no se detienen o bien , es decir , que si el modo de pausa durante 4 días , entonces perderá cuatro días de activar el modo .<br /><br />            Ataques , espionaje y el comercio con una cuenta de pausa es imposible. Solamente los ataques y flota intercambios que están en curso al poner en pausa se han completado.<br /><br />       Está estrictamente prohibido el modo de pausa después de realizar un ataque. Debe esperar un mínimo de 1 hora entre el último ataque y enviado su pausa. El incumplimiento de esta regla puede resultar en una sanción tras la denuncia de un jugador .';
$LNG['RULES_57']				= 'Un jugador tiene la oportunidad de prestar su cuenta a otro jugador que ya está registrado en el mismo universo . Sin embargo , la cuenta del préstamo debe tener una duración mínima de 48 horas y no debe exceder el período máximo de 14 días .<br /><br />        El prestamista debe solicitar primero una declaración de préstamo en la parte apropiada del foro Antaris Legacy. Tiene que ser un miembro del personal ha confirmado el préstamo antes de que el jugador «receptor» se conecta a la cuenta .<br /><br />       Durante el plazo del préstamo , el prestamista no se conecta a la cuenta , consulte el apartado de la gestión conjunta ( si el prestamista se conecta al final del préstamo se ha declarado en el foro, a continuación, se evitará que a través incluso sobre el final prematuro del préstamo) .<br /><br />        El jugador «receptor» tiene la prohibición de las acciones militares hostiles en nombre de los cuales se ocupa temporalmente (ataques y espionaje ) . Sin embargo , se permite llevar a cabo en contra de ataques a través de su propia cuenta. El prestamista no está autorizado a transferir su ejército al destinatario. El incumplimiento de esta regla puede resultar en una sanción de este reproductor .<br /><br />        Le prestamista debe confiar en el otro jugador para hacer una cuenta de préstamo . El personal no es responsable de las acciones que se llevan a cabo en nombre del acreedor ( supresión planeta , el cambio de la contraseña o la simple eliminación de la cuenta ) .<br /><br />       Por último , la cuenta del préstamo no anula las reglas de multi- cuenta de operaciones y gestión conjunta . Una cuenta que ha sido prestada no puede ser nombrado por un período mínimo del último período del préstamo multiplicado por 2 ( es decir , si ha realizado un préstamo de 4 días , entonces será ocho días antes de que un nuevo préstamo es posible) .';
$LNG['RULES_58']				= 'Antaris Legado autoriza a la cuenta de la donación . Una persona puede dar su cuenta a otra solamente bajo las siguientes condiciones : el donante desea dejar de jugar o el donante y el receptor quiere intercambiar su cuenta.<br /><br />              Está estrictamente prohibido dar una cuenta en contra de un bien a cambio (a menos que otra cuenta St Ag ) . Recordamos que la cuenta es propiedad de Antaris Legacy.<br /><br />        Además, las donaciones de cuenta deben ser declaradas antes del foro , y por supuesto , un miembro del personal deben ser validados antes de que el regalo es eficaz.<br /><br />        La donación debe cumplir y aprobar las reglas descritas anteriormente. Una donación está completamente validada una vez que la dirección de cuenta de correo electrónico ha sido cambiado por un moderador. El nuevo propietario tendrá que proporcionar su dirección de correo electrónico por PM o correo electrónico .';
$LNG['RULES_59']				= 'La cogestión es tener más personas que se conectan a la misma cuenta para jugar juntos . La co- administración está estrictamente prohibido en Antaris Legacy.<br /><br />       La misma persona titular de la cuenta , sin embargo , se puede conectar a varios lugares diferentes ( dirección IP) . Esto no es considerado como el co-manejo .';
$LNG['RULES_60']				= 'Aextremo límite de las trampas, la malversación y la sanción de la multi - cuenta, el equipo de Antaris Legado se reserva el derecho a bloquear cualquier cuenta a través de una VPN , un proxy de Internet u otros medios para hacer una cuenta anónima .';
$LNG['RULES_61']				= 'Una persona no puede tener varias cuentas en el mismo universo . Dos cuentas se consideran varias cuentas cuando se conectan a la misma dirección IP ( incluso caja de internet, acceso público , cafetería , EDGE, 3G , etc ... ) . Sin embargo , si ambos jugadores no se vuelven a conectar en un plazo de 7 días a través de la misma dirección IP , entonces el multi- cuenta se elimina automáticamente . Se puede ver la lista de jugadores con múltiples cuentas la tuya por ir a la pestaña «Multi - cuenta» de la página «Comercio» .<br /><br />       Los miembros de la misma familia pueden jugar en el mismo universo de Antaris Legacy. Deben aceptar las reglas escritas en este párrafo , no es necesario declarar en el foro .<br /><br />       Está estrictamente prohibido el comercio ( ya sean directos o indirectos , es decir , llevada a cabo por un jugador intermedio ) , la dirección y el espionaje entre los jugadores en varias cuentas . El incumplimiento de esta norma dará lugar a una sanción. jugadores múltiples cuentas pueden , sin embargo , estar en la misma alianza .';
$LNG['RULES_62']				= 'Sólo puede tener una cuenta por universo. La cuenta debe pertenecer a una sola persona ya que la gestión conjunta está prohibido en Antaris Legacy. Si son más para conectar desde el mismo punto de acceso a Internet y, a continuación , nos vemos en el siguiente párrafo : «Multi - cuenta» .<br /><br />       Conexión a través de un móvil puede causar varias cuentas con jugadores que no conoces . Por favor referirse una vez más en "«Multi - cuenta» para obtener más información .<br /><br />        La cuenta sólo pertenece a su propietario . La dirección de correo electrónico indicada en la página de perfil identifica al propietario a una pérdida de la contraseña . Por lo tanto , cuando una cuenta de donación, por favor cambiar la dirección de correo electrónico tan pronto como sea posible .'; */
//CONDITIONS
$LNG['CONDITION_1']				= 'Términos y Condiciones';
$LNG['CONDITION_2']				= 'Introducción';
$LNG['CONDITION_3']				= 'Servicios de Antaris Legacy';
$LNG['CONDITION_4']				= 'Condiciones de Participación';
$LNG['CONDITION_5']				= 'Requisitos previos para usar nuestros servicios';
$LNG['CONDITION_6']				= 'Responsabilidades';
$LNG['CONDITION_7']				= 'Propiedad';
$LNG['CONDITION_8']				= 'Composición y Terminación';
$LNG['CONDITION_9']				= 'Condiciones de afiliación';
$LNG['CONDITION_10']			= 'Terminación por parte del usuario';
$LNG['CONDITION_11']			= 'Resolución por parte de la empresa';
$LNG['CONDITION_12']			= 'Reembolso';
$LNG['CONDITION_13']			= 'Ley de Financiación';
$LNG['CONDITION_14']			= 'Los contenidos, daños y hacks';
$LNG['CONDITION_15']			= 'Contenido';
$LNG['CONDITION_16']			= 'Daño';
$LNG['CONDITION_17']			= 'Los hackers y / o intentos de piratería';
$LNG['CONDITION_18']			= 'Acciones prohibidas';
$LNG['CONDITION_19']			= 'Las acciones del usuario';
$LNG['CONDITION_20']			= 'Programas';
$LNG['CONDITION_21']			= 'Robo';
$LNG['CONDITION_22']			= 'Inicio de sesión automático';
$LNG['CONDITION_23']			= 'Reglas y limitaciones';
$LNG['CONDITION_24']			= 'Número de cuenta';
$LNG['CONDITION_25']			= 'Reglas';
$LNG['CONDITION_26']			= 'No respeto';
$LNG['CONDITION_27']			= 'Los datos personales CNIL';
$LNG['CONDITION_28']			= 'Copia de seguridad de datos';
$LNG['CONDITION_29']			= 'Comunicación';
$LNG['CONDITION_30']			= 'Comisión Nacional de Informática y Libertades';
$LNG['CONDITION_31']			= 'Aplicación y retirada';
$LNG['CONDITION_32']			= 'Google Analytics';
$LNG['CONDITION_33']			= 'La transferencia de datos';
$LNG['CONDITION_34']			= 'Los derechos comerciales en las cuentas';
$LNG['CONDITION_35']			= 'Visión de conjunto';
$LNG['CONDITION_36']			= 'Prohibición de explotación';
$LNG['CONDITION_37']			= 'Excepción';
$LNG['CONDITION_38']			= 'Elementos del juego';
$LNG['CONDITION_39']			= 'Modificaciones';
$LNG['CONDITION_40']			= 'Términos y Condiciones';
/* $LNG['CONDITION_41']			= 'Estos términos y condiciones fueron publicada el 10 de noviembre de 2011 y son de aplicación inmediata . Antaris legado puede actualizar en cualquier momento estos términos y condiciones , siempre que los usuarios estén informados .';
$LNG['CONDITION_42']			= 'Para el juego Antaris Legacy, el usuario debe aceptar estos términos y condiciones . Se refieren principalmente a los servicios en línea o lo que sigue .<br /><br />             Además de las condiciones generales que se aplicarán al conjunto de reglas . En caso de inconsistencias entre estas condiciones de uso y las reglas del juego , es lo establecido en las condiciones generales que tendrán mayor puntuación .';
$LNG['CONDITION_43']			= 'Nuestros sitios web están optimizados para la navegación a través de un ordenador de sobremesa o un portátil. Por lo tanto , no podemos garantizar la disponibilidad y el flujo de nuestros servicios en otros medios de comunicación tales como teléfonos inteligentes y tabletas .<br /><br />        El usuario debe tener la última versión estable de su navegador web para unirse y utilizar nuestros servicios . Además , tiene que tener una web de los navegadores compatibles con nuestras plataformas, incluyendo la lista completa:<ul>         <li>Mozilla Firefox</li>         <li>Google Chrome</li>       </ul>        Nuestra empresa no se hace responsable de los fallos y errores en el caso de incumplimiento de estos requisitos.';
$LNG['CONDITION_44']			= 'Aunque Antaris legado debe garantizar que todos los servicios están funcionando correctamente , es posible que determinadas situaciones o circunstancias que están fuera de nuestro control. Pueden conducir a una parada momentánea o mal funcionamiento por tiempo indefinido. De este modo , el usuario puede tener ninguna demanda para el buen funcionamiento de los beneficios y servicios proporcionados por el legado Antaris .<br /><br />        Antaris legado no se hace responsable de un mal funcionamiento con uno de sus servidores o mala programación ( esto es sólo un ejemplo entre otros ) .<br /><br />         Sin embargo, el personal de Antaris Legado hará todo lo posible para resolver lo más rápidamente posible los defectos de sus servicios .';
$LNG['CONDITION_45']			= 'Todos los servicios que ofrecemos , incluyendo las cuentas y partidas de sus cuentas son propiedad de Antaris Legacy. Se ponen a disposición de los jugadores .<br /><br />        Los elementos disponibles para los usuarios son objetos virtuales . Están prohibidas las transacciones reales en una cuenta ( por ejemplo, una cuenta de donaciones a cambio de bienes materiales está estrictamente prohibido ) .<br /><br />       Una cuenta de usuario no es transferible sin la aprobación expresa de Antaris heredado o sus representantes .';
$LNG['CONDITION_46']			= ' Cuando un jugador se registra en el juego o en el foro , debe aceptar las condiciones aquí presentes .<br /><br />        La membresía es sólo posible para las personas físicas . El permiso para el uso es sólo como individuos (no grupos , familias , etc ... ) . Si el usuario 13 o menores de 13 años , debe garantizar estar en posesión de un permiso válido de su representante legal .<br /><br />        Tras la adhesión, el usuario debe especificar un nombre de jugador y una dirección de correo electrónico válida. Antaris Legado se reserva el derecho de verificar la validez en cualquier momento y tomar las medidas necesarias en caso de invalidez .<br /><br />        La dirección de correo electrónico utilizada para identificar a un propietario por la pérdida de su entrada . Por lo tanto , es imposible transmitir un informe al dueño si la dirección de correo electrónico no es válida .<br /><br />              Cuando se une , usted autoriza Antaris legado que le envíe el boletín de noticias. Sin embargo , puede darse de baja haciendo clic en el enlace déscincription que se encuentra en la parte inferior de cada correo electrónico «Newsletter».';
$LNG['CONDITION_47']			= 'El usuario puede optar por no utilizar los servicios proporcionados por Antaris Legacy. Para esto, se puede eliminar su cuentas de las plataformas de nuestro negocio . Eliminación de cuentas conducen automáticamente a la terminación de estas condiciones . Sin embargo , esta eliminación puede ser retrasado por cuestiones técnicas .<br /><br />             El usuario acepta de forma automática , y sin fuerza en contra de ella , la terminación de este contrato , a falta de más de 90 días ( sin conexión a nuestro servidor ) . Sin embargo , hay varias excepciones que cancelan la cancelación después de la inactividad : la cuenta está en pausa o se ha realizado al menos una compra en el juego.<br /><br />             Antaris Legado se reserva el derecho a dar cuenta después de un résilitation a través de un sistema de donación automática . Cuando el sistema realiza esta donación , todos los datos personales del usuario , tales como direcciones de correo electrónico , direcciones IP , los mensajes se eliminan de forma permanente .';
$LNG['CONDITION_48']			= 'Si el usuario no cumple con estos términos y condiciones y / o compensación de juego al utilizar nuestros servicios, entonces Antaris Legado se reserva el derecho de eliminar o bloquear ( s ) cuenta ( s ) de la usuario, sin que esto excluye la posibilidad de sanciones adicionales . La eliminación de la cuenta es decidido por el administrador o por uno de los moderadores del servicio en cuestión ( en virtud de los reglamentos de juego , condiciones generales y de derecho francés ) .<br /><br />        Cualquier reclamación por cuenta de borrado pueden ser llevados al foro (en la sección prevista a tal fin ) . No puede haber demandas legales para el cierre de una cuenta. La empresa puede decidir en cualquier momento suspender todos sus servicios y para eliminar todas las cuentas . Para ello, un miembro de la empresa debe notificar a los usuarios antes de la terminación de sus cuentas a través de un mensaje visible en el sitio de Antaris Legacy. En este último caso , el período mínimo entre el anuncio de cierre y suspensión de los servicios ( y por lo tanto , la eliminación de cuentas) es de un mes .';
$LNG['CONDITION_49']			= 'Si el usuario lo solicita , puede ser devuelto dentro de los 14 días siguientes a su compra de PayPal ( válida sólo en las compras a nosotros a través del método de pago «Paypal» ) . Si desea recibir un reembolso por las compras realizadas a través de Allopass , debe comunicarse con su propia manera de obtener un reembolso . Por supuesto , los servicios obtenidos a través de estas compras serán retirados de su cuenta .<br /><br />       Más allá de este período , el reembolso no será tomada por la empresa , incluso en el caso de resolución . De hecho, cuando un usuario acepta un gasto, entonces no se le da el derecho a solicitar un reembolso después de una cancelación por parte del usuario o por la empresa .<br /><br />        Por último , un usuario no puede reclamar el reembolso después de un fallo o error que se produjo en uno de nuestros servicios . Sin embargo , vamos a hacer todo lo posible para corregir los errores que se encuentran en el menor tiempo posible en función de la disponibilidad. Como auto- empresario , es posible que estos plazos son del orden de semanas para los insectos más grandes.';
$LNG['CONDITION_50']			= 'Cuando una cuenta es financiado en parte por un usuario a través de extensiones de pago , que sólo tiene acceso por lo que valió la pena: él puede reclamar nada más que la extensión se compró .<br /><br />              Nos rappeleons que todas las compras realizadas en este sitio web son sólo virtual , y no dan ningún derecho adicional para el usuario en relación a un usuario «lambda» que no han comprado expansión.';
$LNG['CONDITION_51']			= 'Antaris Legacy es un juego , por lo que creó una plataforma para poner a los jugadores en la relación. Sólo el usuario es responsable de lo que desea para los demás. Nuestra empresa no se hace responsable . Por lo tanto , el contenido pornográfico , xenófobo , insulto o ilegales no están permitidos y son los responsables civiles y / o penales .<br /><br />        Sin embargo , la moderación y la administración se esfuerza por borrar y eliminar aproximadamente un usuario infractor . Por otra parte , Antaris Legado se reserva el derecho de bloquear y / o eliminar las cuentas de aquellos usuarios sin previo aviso . Estas sanciones no excluyen cualquier responsabilidad civil y / o penal , si se considere necesaria la compañía .<br /><br />              Del mismo modo , la empresa no se hace responsable de ilegal en cualquiera de sus representantes voluntarios (por ejemplo de moderación ) .';
$LNG['CONDITION_52']			= 'Antaris legado no es responsable de los daños , independientemente de la gravedad , causado por el uso de nuestros servicios . La compañía recuerda a los jugadores que el uso excesivo de vídeo o de computadora puede causar una grave discapacidad física y / o mental. A cada usuario se supone que tiene conocimiento de, y por lo tanto, acepta los riesgos .';
$LNG['CONDITION_53']			= 'La piratería es castigado por la ley . Cualquier intento de piratería o la piratería es pasible de enjuiciamiento . Esto puede relacionarse con los servicios de piratería y servidores de la empresa , sino también para las cuentas de usuario . Cualquier intento de hacking o darán lugar a sanciones, tales como el bloqueo de la cuenta de fallo de dirección o IP . Las sanciones penales para los delitos informáticos pueden ser de hasta 5 años de prisión y una multa de € 75.000 .<br /><br />        Antaris legado ha establecido un sistema de cifrado de datos. Por lo tanto , la piratería una cuenta de jugador sólo puede ser debido a una contraseña demasiado fácil de piratear (o es demasiado corto o la contraseña es demasiado simple ) . Te recomendamos no utilizar las palabras de la vida cotidiana , sino que permite componer una contraseña con letras y números que no tienen ningún significado .<br /><br />        El usuario se compromete a mantener las credenciales de acceso estrictamente confidenciales . También requiere no sólo introducir las credenciales de acceso a las páginas del sitio web operado por Antaris Legacy. Por lo tanto , es muy recomendable que el usuario verifique que está en la página de autenticación correcta antes de llenar su código de acceso al iniciar la sesión .<br /><br />        En el caso de incumplimiento de las condiciones escritas anteriormente , la empresa no se hace responsable de cualquier robo o la cuenta de la piratería , así como sus consecuencias .';
$LNG['CONDITION_54']			= 'El usuario no tiene derecho a realizar acciones que frenarían el sitio Antaris Legacy, ya sea a través de un script o algo más. Él no tiene el derecho de bloquear el sitio , modificar o reformular el contenido , o cualquier otro contenido oficial redirigida por un miembro del Legado Antaris sin la previa autorización del administrador .';
$LNG['CONDITION_55']			= 'Está estrictamente prohibido el uso de programas que no sean de un navegador estándar para navegar por nuestro sitio ( uso y visualización ) . Antaris Legacy es particularmente todas las secuencias de comandos o programas llamados «Bot» que pueden realizar acciones de forma automática . El uso de add-ons y secuencia de comandos para simplificar , facilitar y reemplazar a un ser humano está prohibido y dará lugar a fuertes sanciones.<br /><br />              Para limitar hacer trampa en el juego está prohibido Antaris Legacy, el uso de VPN / proxy o otro programa para ocultar el origen y / o la dirección IP del usuario. El acceso al juego está recomendado para todas las personas que deseen mantener su información confidencial.';
$LNG['CONDITION_56']			= 'Está estrictamente prohibido que un usuario pueda hacerse pasar por un miembro de la empresa o un miembro perteneciente a la moderación Antaris Legacy. El miembro del equipo suplantación «virtual» dará lugar a una expulsión definitiva y automática de nuestros servicios .';
$LNG['CONDITION_57']			= 'El usuario debe conectar " manual " de la página principal de Antaris Legacy. Las aberturas y las conexiones automáticas está estrictamente prohibido.';
$LNG['CONDITION_58']			= 'El usuario puede crear una cuenta por universo , de lo contrario lo que se considera un cliente no normativo . La regla anterior se aplica a todos los de nuestro universo , pero puede ser legalizado por un miembro del personal ( lea las reglas para más información) . El cliente no regulador puede ser sancionado sin previo aviso por diversos medios : advertencia, suspensión de las cuentas ofensivas y / o eliminación de cuentas .';
$LNG['CONDITION_59']			= 'Cuando un jugador ha registrado en uno de nuestro universo , en uno de nuestros sitios o en el foro , debe aceptar las condiciones generales (en la actualidad) y la regulación de servicios a la que se adhiere . Por lo tanto , él sabe todas las reglas y condiciones que los ha leído y aceptado generales .';
$LNG['CONDITION_61']			= 'Tras el incumplimiento de las reglas de juego o condiciones generales , el usuario puede bloquear temporal o permanentemente . El bloqueo puede ser válido en una parte o la totalidad de los servicios ofrecidos por Antaris Legacy.';
$LNG['CONDITION_62']			= 'Legado de copia de seguridad antaris sus datos personales con el fin de verificar el cumplimiento de las reglas del juego y las condiciones generales . Estos datos pueden ser ( dirección IP , la hora de inicio de sesión , el navegador utilizado , el sistema operativo , dirección de correo electrónico proporcionada durante el registro ) técnico, pero también puede ser una estadística ( número de compras , la edad medio , el sexo ) o incluso personal.<br /><br />        Estos datos podrían proporcionarse a petición de la empresa al crear la cuenta , o , en su caso, proporcionados voluntariamente por el usuario.<br /><br />             Antaris Legado hace todo lo posible para salvar sus datos personales de forma segura . Sin embargo , la empresa no se hace responsable de la filtración de estos datos en caso de piratería de uno de sus servicios.';
$LNG['CONDITION_63']			= 'Antaris Legado se reserva el derecho a comunicar todos estos datos a las autoridades francesas con el fin de proteger sus intereses o en el caso de posibles violaciones del Derecho .';
$LNG['CONDITION_64']			= 'Recordamos a nuestros usuarios que, por el respeto de la protección de sus datos personales , que se detalla en este apartado, Antaris legado está registrada en la CNIL bajo el número 1538743 (clientes - prospectos Archivos ) y Nº 1.538.741 ( estadísticas tratamientos) .';
$LNG['CONDITION_65']			= 'Vou puede pedir Antaris legado de proporcionar ningún dato personal sobre usted , para esto, por favor, póngase en contacto con nosotros a través del siguiente correo electrónico : staff@antaris-legacy.co . Si solicita la eliminación de sus datos personales , esto dará lugar automáticamente a la eliminación o rescisión de todas sus cuentas de usuario .';
$LNG['CONDITION_66']			= 'Antaris Legado utiliza Google Analytics , un servicio de análisis web de Google Inc. ( Google ) .<br /><br />        Google Analytics utiliza cookies, que son archivos de texto ubicados en su ordenador, para ayudar al website a analizar el uso del sitio por sus usuarios . Los datos generados por la cookie acerca de su uso del website (incluyendo su dirección IP) será transmitida y almacenada por Google en los servidores de Estados Unidos .<br /><br />             Google usará esta información para evaluar su uso del sitio web , recopilando informes de la actividad del sitio web a la herencia Antaris y prestando otros servicios relacionados con la actividad del sitio web y el uso Internet.<br /><br />              Google podrá transmitir dicha información a terceros cuando sea requerido por la ley , o cuando dichos terceros procesen la información por cuenta de Google , incluyendo , en particular, el editor de este sitio . Google no asociará su dirección IP con otros datos de Google .<br /><br />       Puede desactivar el uso de cookies, mediante la selección de la configuración apropiada de su navegador . Sin embargo , esta desactivación podría impedir el uso de algunas funciones de este sitio web. El uso de plataformas Antaris heredados , que consiente el tratamiento de los datos por Google en la forma y para los fines descritos anteriormente .';
$LNG['CONDITION_67']			= 'Sus datos de carácter personal , naturalmente, no serán vendidos a terceros . Sin embargo , Antaris Legado transmitir a terceros los datos personales facilitados por usted , además del uso de Google Analytics, sólo en los siguientes casos : los proveedores de servicios de pago ( PayPal , Allopass ) , anfitrión ( OVH ) . Estos proveedores de servicios tienen acceso a sus datos personales en la medida les permitió permite completar sus misiones . Estos proveedores están obligados a procesar sus datos personales de acuerdo con esta declaración de protección de datos personales y las leyes básicas que rigen la protección de datos .';
$LNG['CONDITION_68']			= 'Todas las cuentas son propiedad de Antaris Legacy. Es lo mismo para todos los elementos que lo integran ( las cuentas) , como los recursos , unidades, edificios , tecnologías, etc ... Ninguna ley , en particular las relativas a la operación , no puede ser concedido para el usuario.';
$LNG['CONDITION_69']			= 'En general , sin el permiso por escrito de la empresa , se prohíbe contratar con un tercero ningún acuerdo sobre la transferencia , uso o almacenamiento de cuentas o datos personales . Por lo que se prohíbe en particular para vender cuentas o recursos (u otro componente de una cuenta) o para obtener un beneficio dejando dicha cuenta (o uno de sus componentes ) a favor de un tercero en en efecto, es aún la propiedad de Antaris legado y por lo tanto no puede ser objeto de transacción.<br /><br />       Las mismas prohibiciones se aplican a los datos y los derechos de uso personal . Es particularmente pertinente en este caso , cualquier transacción en contra de Allopass , o cualquier cosa de valor .<br /><br />       La violación de estas reglas o cualquier otro derecho de la sociedad , en particular las relativas derechos de autor , se remitirá a las autoridades y confirmado por civil y / o penal. Sanciones adicionales también pueden ser tomadas por la empresa , incluido el bloqueo de todas las cuentas del usuario infractor .';
$LNG['CONDITION_70']			= 'Es posible dar una cuenta gratuita a otro usuario , o intercambio . Sin embargo , estas acciones deben respetar las reglas .';
$LNG['CONDITION_71']			= 'La empresa puede realizar cambios en el código fuente del juego , sobre el funcionamiento y las características de los elementos virtuales (construcción, tecnología , dispositivos, etc ... ) en cualquier momento y sin previo aviso y sin la necesidad de prevenir usuarios.<br /><br />             El conjunto de elementos virtuales disponibles para el jugador puede estar sujeto a cambios y / o retirada sin que el usuario puede desafiar ( a menos que elimine su cuenta) .';
$LNG['CONDITION_72']			= 'Antaris Legado se reserva el derecho de modificar ( en general ) las condiciones generales y demás disposiciones en cualquier momento. Estas modificaciones o extensiones serán efectivas tan pronto como miembro del Legado Antaris anunciar estos cambios en un medio de comunicación web.<br /><br />         Una vez válida , estos cambios tienen efecto retroactivo : todas las cuentas ya creadas , así como todas las acciones en proceso , o todavía no transformados , se someten a las nuevas disposiciones , sin que el jugador pueda oponerse a que de otro modo mediante la supresión de su cuenta.'; */
